### ISSUE TITLE
Improve fs.CopyFromOs function

### ISSUE THREAD

**Issue by dominikbraun** [verless/verless#200]
`fs.CopyFromOs` copies a file from the host to another filesystem. The current implementation looks as follows:

**1. Read the source file**

https://github.com/verless/verless/blob/568bc63459b071b710d8fc496fb1ecf6234f948d/fs/fs.go#L118-L121

**2. Create the destination file**

https://github.com/verless/verless/blob/568bc63459b071b710d8fc496fb1ecf6234f948d/fs/fs.go#L136-L139

**3. Write the source contents into the destination file**

https://github.com/verless/verless/blob/568bc63459b071b710d8fc496fb1ecf6234f948d/fs/fs.go#L140-L142

This works well, but can be optimized to achieve a slightly better performance according to [3 ways to copy files in Go](https://opensource.com/article/18/6/copying-files-go).

**Optimizations**

* Reading the source file should be done using `os.Open` instead of `ioutil.ReadFile`.
* Writing the source contents should be done using ~~`os.Copy`~~ `io.Copy` instead of `io.Writer.Write`.
* Both files should be closed at the end of the loop.

**Comment by rehanvipin** [comment]
Hi!
I would like to work on this issue.  

In the second point under optimizations do you mean `io.Copy` instead of `os.Copy`? Just like they've used in this link [3 ways to copy files in Go](https://opensource.com/article/18/6/copying-files-go). I couldn't find `os.Copy` under the `os` package.
I've done the other optimizations (just making sure it adheres to the contribution guidelines before submitting a PR) and tested with the given tests (they pass).  

The detailed explanation, links to code and clear requirements really helped in getting started.  
Thank you for your time and effort!  

P.S. Sorry to bother you so much, how do you configure **verless** so that `go install` installs the executable in `$GOPATH/bin/`? (If it's possible. I'm using the target generated by the makefile for now)

**Comment by aligator** [comment]
Hi,
> P.S. Sorry to bother you so much, how do you configure **verless** so that `go install` installs the executable in `$GOPATH/bin/`? (If it's possible. I'm using the target generated by the makefile for now)
This should work:
`cd cmd/verless && go install`

**Comment by dominikbraun** [comment]
>In the second point under optimizations do you mean io.Copy instead of os.Copy? Just like they've used in this link 3 ways to copy files in Go. I couldn't find os.Copy under the os package.

Sorry, my bad. I meant `io.Copy` of course.

**Comment by rehanvipin** [comment]
I'm posting this here since I'm not sure where it belongs (new issue?).  
I found the code really clear and easy to work with, I would like to contribute more.  

While testing the code it seemed to work all fine, but then I noticed there aren't any test for fs. (I just realized I claimed the tests were passing even though there aren't any tests :P)
If you aren't already working on it, maybe I could start by writing tests for fs?  

Being honest, I haven't written a lot of tests in Go, I would like to work on it more, and since I'm unfamiliar with the testing structure of this project I have a few questions too.   
Before I get too ahead of myself, what are your opinions on this? Is testing the other packages a part of the current goal?

**Comment by dominikbraun** [comment]
> I found the code really clear and easy to work with, I would like to contribute more.

Great to hear that, and in case you find some code that is hard to understand for you or could be improved, just open an issue and don't hesitate to ask anything. There's nothing to lose.

> If you aren't already working on it, maybe I could start by writing tests for fs?

Funny, because yesterday @aligator and I found that the `fs` package is the only mission-critical package that isn't tested yet, and it definitely should be. Feel free to create tests for `fs` or any other package or function that isn't tested yet - all tests are structured identically and we're happy to answer your questions.
